name: Daily Commit

on:
  schedule:
    - cron: '30 14 * * *'  # Runs at 14:30 UTC daily

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Git config (mohit.dubey@gramener.com)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "mohit.dubey@gramener.com"
          
      - name: Create and commit daily update
        run: |
          echo "Daily update $(date)" >> daily-updates.txt
          git add daily-updates.txt
          git commit -m "Daily automated commit $(date)"
          git push
