name: Daily Commit Workflow

on:
  schedule:
    # Runs at 10:30 AM UTC (specific time as required)
    - cron: '30 10 * * *'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  create-daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Git Config (mohit.dubey@gramener.com)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "mohit.dubey@gramener.com"
          
      - name: Create and commit daily update
        run: |
          # Create or update a file with current timestamp
          echo "Last updated: $(date)" > last_update.txt
          
          # Add and commit the changes
          git add last_update.txt
          git commit -m "Daily automated update $(date)"
          git push
